
                  try {
                        
                           
                           // Something that may throw an exception.
                           ...
                     } catch (Throwable t) {logger.error("Caught: " + t.toString());return;}
               
            